### ISSUE TITLE
Prototype Pollution on merge dependency

### ISSUE THREAD

**Issue by LukasCornille** [zeke/npe#20]
Hi, when installing this package in my repo. The merge dependency in your package has a security advisory related to Prototype Pollution, could you update the dependency?

Here's a screenshot of the issue!
![image](https://user-images.githubusercontent.com/36887321/119456723-40a1d580-bd3b-11eb-8acf-aa3a877a0d11.png)

**Comment by zeke** [comment]
Hello. I would gladly accept a PR that updates this! 🙏🏼
